---
#handlers:

            
              
    #when: ansible_distribution == 'Debian'


      #shell: git clone https://github.com/firehol/netdata.git /tmp/netdata --depth=1 && 
               #cd /tmp/netdata &&
               #./netdata-installer.sh --dont-start-it
      #notify:
        #- restart Netdata
        
    #- name: restart Netdata
      #service:
        #name: netdata.service
        #state: restarted
