---
#tasks:
  
# Installing application packages and managing services
- include: Pkg.yml

# User&groups
- include: Usr.yml

# LXDM conf
# - include: LXDM.yml

# Language setup
- include: Lang.yml

#  - name: Open en_US.UTF-8 locale in config
#    shell: 'sed -i "s/^# en_US.UTF-8/en_US.UTF-8/" /etc/locale.gen'
  

      
#  - name: Install Tor Browser
#  apt-get install torbrowser-launcher -t stretch-backports
  
#        - torbrowser
#        - deadbeef
#        - GIMP
#    - LibreOffice?
#    - Games
# 
# Pysolfc
# Blobby
# Supertux
# Sgt-puzzles
# Extremetuxracer
# Funguloids

# Ace-of-penguins 

# Berusky 
# PyChess Gmome Chess
# Caveexpress 
# Frozen-bubble 
# Gnubg
# Gweled
# Hedgewars
# Lbreakout2 
# Numptyphysics

# Supertuxkart
# 
#   
#    - Skype
#    - Viber
#    - Telegram

#  - name: Removing junk packages
#    apt:
#      state: absent
#      name:
#        - konqueror
#        - kopete
#        - kmail
#        - juk
#        - k3b
#        - dragonplayer
#        - akregator
#        - ktnet
#        - kontactl
        
- name: Autoclean Autoremove
  apt:
    autoremove: yes
    autoclean: yes
