---
#tasks:

#  - name: Disable SDDM service
#    service:
#      name: sddm.service
#      state: stopped
#      enabled: no

#  when: ansible_os_family == "Debian"

  - name: Workaround, installing aptitude (https://github.com/ansible/ansible/issues/18987)
    apt:
      name:
        - aptitude
  
  - name: Repos open Contrib and Non-free
    apt_repository:
      repo: deb http://ftp.ua.debian.org/debian/ stretch contrib non-free
      
  - name: Updating system
    apt:
      upgrade: full
      
#- name: Install Firefox...

      
#  - name: Debian Multimedia Unofficial repository
#    apt_repository:
#      repo: deb http://www.deb-multimedia.org stretch main non-free
      
#  - name: Debian Multimedia Unofficial keyring
#    apt:
#      name: deb-multimedia-keyring
      
      
  - name: Install packages
    apt:
      name:
        - mpv
        - smplayer
        - inkscape
        - qbittorrent
        - pidgin
        - eog
        - kvkbd
        - wine
        - kde-l10n-ru
        
  
  - name: Install LXDM
    apt:
      name:
        - lxdm
      install_recommends: no
      
  - name: Firefox experimental repository
    apt_repository:
      repo: deb http://http.debian.net/debian experimental main
      
  - name: Firefox package
    command: apt install -y -t experimental firefox
  
  - name: Firefox Localization
    apt:
      name: firefox-l10n-ru

#  - name: Running LXDM service
#    service:
#      name: lxdm.service
#      state: started
#      enabled: yes
  
  #- name: Installing X2Go

  - name: X2Go Dev key
    apt_key:
      keyserver: keys.gnupg.net
      id: E1F958385BFE2B6E
      
  - name: X2Go APT repository
    apt_repository:
      repo: deb http://packages.x2go.org/debian stretch main
      
  - name: X2Go Keyring package
    apt:
      name: x2go-keyring
      
  - name: X2Go X2Go server package
    apt:
      name:
        - x2goserver
        - x2goserver-xsession
      update_cache: yes

  - name: Running X2Go service
    service:
      name: x2goserver.service
      state: started
      enabled: yes
  
  - name: Install TeamViewer
    apt:
      deb: https://download.teamviewer.com/download/teamviewer_i386.deb

  - name: Running TeamViewer service
    service:
      name: teamviewerd.service
      state: started
      enabled: yes
  
#  - name: Install Tor Browser
#  apt-get install torbrowser-launcher -t stretch-backports
  
#        - torbrowser
#        - deadbeef
#        - GIMP
#    - LibreOffice?
#    - Games
# 
# Pysolfc
# Blobby
# Supertux
# Sgt-puzzles
# Extremetuxracer
# Funguloids

# Ace-of-penguins 

# Berusky 
# PyChess Gmome Chess
# Caveexpress 
# Frozen-bubble 
# Gnubg
# Gweled
# Hedgewars
# Lbreakout2 
# Numptyphysics

# Supertuxkart
# 
#   
#    - Skype
#    - Viber
#    - Telegram
#    - TeamViewer
#    - DeadBeef

#  - name: Removing junk packages
#    apt:
#      state: absent
#      name:
#        - konqueror
#        - kopete
#        - kmail
#        - juk
#        - k3b
#        - dragonplayer
#        - akregator
#        - ktnet
#        - kontactl
        
  - name: Autoclean Autoremove
    apt:
      autoremove: yes
      autoclean: yes
