---
#tasks:

#  - name: Disable SDDM service
#    service:
#      name: sddm.service
#      state: stopped
#      enabled: no

#  when: ansible_os_family == "Debian"

  - name: Workaround, installing aptitude (https://github.com/ansible/ansible/issues/18987)
    apt:
      name:
        - aptitude
  
  - name: Repos open Contrib and Non-free
    apt_repository:
      repo: deb http://ftp.ua.debian.org/debian/ stretch contrib non-free
      
  - name: Updating system
    apt:
      upgrade: full
      
#- name: Install Firefox...

      
#  - name: Debian Multimedia Unofficial repository
#    apt_repository:
#      repo: deb http://www.deb-multimedia.org stretch main non-free
      
#  - name: Debian Multimedia Unofficial keyring
#    apt:
#      name: deb-multimedia-keyring
      
      
  - name: Install packages
    apt:
      name:
        - mpv
        - smplayer
        - inkscape
        - qbittorrent
        - pidgin
        - eog
        - kvkbd
        - wine
        - kde-l10n-ru
        - fonts-liberation
        - ttf-mscorefonts-installer
      state: present
  
  - name: Install LXDM
    apt:
      name:
        - lxdm
      install_recommends: no
      
  - name: Firefox experimental repository
    apt_repository:
      repo: deb http://http.debian.net/debian experimental main
      
  - block:
    - name: Firefox package present?
      apt:
        name: firefox
        state: present
    rescue:
      - name: Installing Firefox package
        command: apt install -y -t experimental firefox
  
  - name: Firefox Localization
    apt:
      name: firefox-l10n-ru

#  - name: Running LXDM service
#    service:
#      name: lxdm.service
#      state: started
#      enabled: yes
  
  #- name: Installing X2Go

  - name: X2Go Dev key
    apt_key:
      keyserver: keys.gnupg.net
      id: E1F958385BFE2B6E
      
  - name: X2Go APT repository
    apt_repository:
      repo: deb http://packages.x2go.org/debian stretch main
      
  - name: X2Go Keyring package
    apt:
      name: x2go-keyring
      
  - name: X2Go X2Go server package
    apt:
      name:
        - x2goserver
        - x2goserver-xsession
      update_cache: yes

  - name: Running X2Go service
    service:
      name: x2goserver.service
      state: started
      enabled: yes
  
  - name: Install TeamViewer
    apt:
      deb: https://download.teamviewer.com/download/teamviewer_i386.deb

  - name: Running TeamViewer service
    service:
      name: teamviewerd.service
      state: started
      enabled: yes
      
  - name: Install DeadBeef
    apt:
      deb: https://sourceforge.net/projects/deadbeef/files/debian/deadbeef-static_0.7.2-2_i386.deb/download
  
  - name: Group Olya
    group:
      name: olya
  
  - name: User Olya
    user:
      name: olya
      group: olya
      groups:
        - olya
        - cdrom
        - floppy
        - audio
        - dip
        - video
        - plugdev
        - netdev
        - bluetooth
        - lpadmin
        - scanner
        - users
        - disk
        - games
  
  - name: LXDM default display manager
    shell: 'sed -i "s%^/usr/bin/sddm%/usr/bin/lxdm%" /etc/X11/default-display-manager'
    
  - name: Open LXDM for Olya autologin
    shell: 'sed -i "s/^# autologin=dgod/autologin=olya/" /etc/lxdm/lxdm.conf'
    
  - name: KDE as default LXDM login
    shell: 'sed -i "s%^# session=/usr/bin/startlxde%session=/usr/bin/startkde%" /etc/lxdm/lxdm.conf'
    
  - name: Permit passwordless LXDM login
    shell: 'sed -i "s/^# skip_password=1/skip_password=1/" /etc/lxdm/lxdm.conf'
  
#  - name: Open en_US.UTF-8 locale in config
#    shell: 'sed -i "s/^# en_US.UTF-8/en_US.UTF-8/" /etc/locale.gen'
  
  - name: Open ru_RU.UTF-8 locale in config
    shell: 'sed -i "s/^# ru_RU.UTF-8/ru_RU.UTF-8/" /etc/locale.gen'
  
  - name: Open ru_UA.UTF-8 locale in config
    shell: 'sed -i "s/^# ru_UA.UTF-8/ru_UA.UTF-8/" /etc/locale.gen'
    
  - name: Build locales
    shell: locale-gen
    
  - name: Creating /home/olya/.config/
    file:
      path: /home/olya/.config
      state: directory
  
  - name: Check permissions for /home/olya/.config/
    file:
      path: /home/olya/.config
      owner: olya
      group: olya
    
  - name: Populating locale preferences
    blockinfile:
      create: yes
      path: /home/olya/.config/locale.conf
      block: |
        LANG=ru_RU.UTF-8
        LANGUAGE=ru_RU:ru_UA:en_US
        LC_NUMERIC=ru_RU.UTF-8
        LC_TIME=ru_RU.UTF-8
        LC_MONETARY=ru_UA.UTF-8
        LC_MESSAGES=ru_RU.UTF-8
        LC_PAPER=ru_RU.UTF-8
        LC_NAME=ru_RU.UTF-8
        LC_ADDRESS=ru_RU.UTF-8
        LC_TELEPHONE=ru_UA.UTF-8
        LC_MEASUREMENT=ru_RU.UTF-8
  
  - name: Check locale preferences file permissions
    file:
      path: /home/olya/.config/locale.conf
      owner: olya
      group: olya
    
#  - name: Install Tor Browser
#  apt-get install torbrowser-launcher -t stretch-backports
  
#        - torbrowser
#        - deadbeef
#        - GIMP
#    - LibreOffice?
#    - Games
# 
# Pysolfc
# Blobby
# Supertux
# Sgt-puzzles
# Extremetuxracer
# Funguloids

# Ace-of-penguins 

# Berusky 
# PyChess Gmome Chess
# Caveexpress 
# Frozen-bubble 
# Gnubg
# Gweled
# Hedgewars
# Lbreakout2 
# Numptyphysics

# Supertuxkart
# 
#   
#    - Skype
#    - Viber
#    - Telegram

#  - name: Removing junk packages
#    apt:
#      state: absent
#      name:
#        - konqueror
#        - kopete
#        - kmail
#        - juk
#        - k3b
#        - dragonplayer
#        - akregator
#        - ktnet
#        - kontactl
        
  - name: Autoclean Autoremove
    apt:
      autoremove: yes
      autoclean: yes
